[package]
name = "iro"
version = "0.0.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
topcoat = { version = "0.8.1", features = ["tailwind"] }

[dev-dependencies]
anyhow = "1.0.104"

[build-dependencies]
topcoat = { version = "0.8.1", default-features = false, features = [
    "tailwind",
] }
